import { ApiProperty } from "@nestjs/swagger";
import {
  IsHexadecimal,
  ValidateNested,
  IsNotEmpty,
} from "class-validator";
import { Type } from "class-transformer";
import { ForwardRequestDto } from "./forward-request.dto";

/**
 * Gasless Transaction Request DTO
 * Complete API request structure including ForwardRequest and signature
 *
 * SPEC-GASLESS-001: Gasless Transaction API
 * - U-GASLESS-001: EIP-712 Signature Verification
 * - T-GASLESS-003: DTO Validation
 */
export class GaslessTxRequestDto {
  /**
   * ForwardRequest structure (EIP-712 typed data)
   * Contains all transaction details that were signed
   */
  @ApiProperty({
    description: "ForwardRequest structure",
    type: ForwardRequestDto,
  })
  @ValidateNested()
  @Type(() => ForwardRequestDto)
  @IsNotEmpty()
  request: ForwardRequestDto;

  /**
   * EIP-712 signature
   * The signature of the typed ForwardRequest data
   * Generated by the client using ethers.signTypedData()
   * Example: 0x1234...
   */
  @ApiProperty({
    description: "EIP-712 signature",
    example: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1c",
  })
  @IsHexadecimal()
  signature: string;
}
